In [1]:
from calculations.Composition.Composition import Composition
from calculations.Utils.Conditions import Conditions
from calculations.CompositionalModel.CompositionalModel import CompositionalModel
from calculations.EOS.PenelouxVolumeCorrection import PenelouxVolumeCorrection
from calculations.Utils.ResultsViewer import FlashResultsViewer, DLEResultsViewer, SeparatorTestResultsViewer, StandardSeparationResultsViewer
from calculations.Utils.CompositionLoader import CompositionExcelLoader

# KRSNLN

In [ ]:
excel_loader = CompositionExcelLoader(r'C:\Users\user\Desktop\PVT_TSU\diss\krsnln.xlsx')
krsnln_dict = excel_loader.load(header=True, sheet='to_model')

In [ ]:
krsnln_dict

In [ ]:
krsnln_base_composition = Composition(zi = krsnln_dict)

In [ ]:
krsnln_model = CompositionalModel(krsnln_base_composition, eos= 'PREOS')

In [ ]:
conds = Conditions(5,50)
krsnln_model.flash(conditions=conds)

In [ ]:
krsnln_model.show_flashes

In [ ]:
krsnln_model.experiments.SEPARATORTEST.calculate_3stages([0.7, 0.5, 0.1], [20, 20, 20])

In [ ]:
krsnln_model.experiments.SEPARATORTEST.result

In [ ]:
from calculations.Utils.ResultsViewer import SeparatorTestResultsViewer

sep_test_view = SeparatorTestResultsViewer()
sep_test_view.view(krsnln_model.experiments.SEPARATORTEST.result)

# PRRZLM №200839

In [2]:
excel_loader = CompositionExcelLoader(r'C:\Users\user\Desktop\PVT_TSU\diss\prrzlm.xlsx')
przlm_dict = excel_loader.load(header=True, sheet='to_model')

### Фактические данные

In [79]:
p_sat = 120.47

## Создаем базовую модель и сравниваемся с PVTSIM

In [3]:
przlm_comp = Composition(przlm_dict)

In [4]:
przlm_model = CompositionalModel(przlm_comp)

In [5]:
conds = Conditions(5,50)

In [6]:
przlm_model.flash(conds)

In [7]:
przlm_model.saturation_pressure(60)

SATURATION PRESSURE CALCULATION
=====
CALCULATED SATURATION PRESSURE: 85.35510856474869 bar
TEMPERATURE: 60 C

### Проверяем сепаратор тест

In [8]:
przlm_model.experiments.SEPARATORTEST.calculate_3stages([0.7, 0.5, 0.1], [20, 20, 20])

SeparatorTestResults(first_stage_pressure=0.7, first_stage_temperature=293.14, first_stage_fv=0.2861830815188178, first_stage_fl=0.7138169184811822, first_stage_vapour_composition={'CO2': 0.0029932677287709797, 'N2': 0.04090762837866887, 'C1': 0.8455156478353413, 'C2': 0.07249921176560595, 'C3': 0.025001469679088433, 'iC4': 0.0030182128152255656, 'nC4': 0.006183186143875353, 'iC5': 0.0013864810540705954, 'nC5': 0.0009647890905620216, 'C6': 0.0006899637678559609, 'C7': 0.00045716462315847087, 'C8': 0.0002677062185067711, 'C9': 7.627626308400961e-05, 'C10': 2.361043749410221e-05, 'C11': 7.913562093545391e-06, 'C12': 2.910790380170107e-06, 'C13': 1.0552135609902687e-06, 'C14': 3.467166589485652e-07, 'C15': 1.0748351262488413e-07, 'C16': 3.5156093032476375e-08, 'C17': 9.534763243779457e-09, 'C18': 3.5222215671723997e-09, 'C19': 1.4433624424841594e-09, 'C20': 5.30103980894262e-10, 'C21': 1.5696826254973423e-10, 'C22': 6.131901202427214e-11, 'C23': 1.8261377590468838e-11, 'C24': 6.251025094487469e-12, 'C25': 2.1336804632047265e-12, 'C26': 6.700768625361996e-13, 'C27': 2.1969669301321275e-13, 'C28': 6.900001882277934e-14, 'C29': 2.94960351711506e-14, 'C30': 1.1797926186011562e-14, 'C31': 3.7333009764936694e-15, 'C32': 1.0832338409976402e-15, 'C33': 6.815618852474186e-16, 'C34': 1.9562440879921733e-16, 'C35': 5.598053759200253e-17, 'C36': 5.045097622319405e-16}, first_stage_liquid_composition={'CO2': 0.000518868925602878, 'N2': 0.0005728763810137741, 'C1': 0.03366651281008557, 'C2': 0.016925841705938867, 'C3': 0.021148283227665113, 'iC4': 0.006476784783549564, 'nC4': 0.019092398040577645, 'iC5': 0.01089945107497998, 'nC5': 0.010103282085821483, 'C6': 0.0189804187768573, 'C7': 0.03892197915187904, 'C8': 0.0617852923734094, 'C9': 0.0517880286483549, 'C10': 0.04594769645139276, 'C11': 0.042042622548467135, 'C12': 0.0436935104415875, 'C13': 0.04379231873943812, 'C14': 0.04132698456955362, 'C15': 0.039989202414497896, 'C16': 0.03730647067819951, 'C17': 0.03024584695645769, 'C18': 0.027057356714232796, 'C19': 0.025821746598767396, 'C20': 0.024695407732561216, 'C21': 0.019844023850286146, 'C22': 0.02013121237449398, 'C23': 0.016165209447999505, 'C24': 0.014379037162708611, 'C25': 0.013521674465108413, 'C26': 0.011933031817083203, 'C27': 0.011453917367682375, 'C28': 0.010099228266148608, 'C29': 0.011210157384638271, 'C30': 0.01064138409069786, 'C31': 0.008965884436609426, 'C32': 0.006508671733201808, 'C33': 0.010525107776915017, 'C34': 0.007260965474211549, 'C35': 0.005641502597848757, 'C36': 0.12891680992347587}, first_stage_vapour_z=0.9793248260305522, first_stage_liquid_z=0.08897254456973983, first_stage_k_values={'CO2': 5.7688321290258, 'N2': 71.40742703736166, 'C1': 25.11444094625826, 'C2': 4.283344546473439, 'C3': 1.182198545855617, 'iC4': 0.4660048027057419, 'nC4': 0.3238559205990804, 'iC5': 0.1272065028351111, 'nC5': 0.09549264114044341, 'C6': 0.036351345877427596, 'C7': 0.011745667438301383, 'C8': 0.004332846996803791, 'C9': 0.0014728551187366467, 'C10': 0.0005138546503431193, 'C11': 0.00018822712794432748, 'C12': 6.661836851175994e-05, 'C13': 2.4095859533465926e-05, 'C14': 8.389594899309399e-06, 'C15': 2.6878133629871173e-06, 'C16': 9.423591241242839e-07, 'C17': 3.152420647206813e-07, 'C18': 1.3017611455444315e-07, 'C19': 5.589716547497443e-08, 'C20': 2.1465690570288214e-08, 'C21': 7.910102494029747e-09, 'C22': 3.0459671719504902e-09, 'C23': 1.1296715733385525e-09, 'C24': 4.347318268777566e-10, 'C25': 1.5779705898929282e-10, 'C26': 5.6153111196512905e-11, 'C27': 1.918092177206504e-11, 'C28': 6.8322070760653125e-12, 'C29': 2.631188319583292e-12, 'C30': 1.10868342740534e-12, 'C31': 4.163895935631164e-13, 'C32': 1.6642932466111108e-13, 'C33': 6.47558105525822e-14, 'C34': 2.6941927970048605e-14, 'C35': 9.922983570609235e-15, 'C36': 3.9134521132768794e-15}, first_stage_vapour_mw=18.975597807753488, first_stage_liquid_mw=232.31335093395796, first_stage_vapour_volume=975.3237213842834, first_stage_liquid_volume=221.01457561823474, first_stage_vapour_density=0.0055678898556646185, first_stage_liquid_density=0.7503088871937443, second_stage_pressure=0.5, second_stage_temperature=293.14, second_stage_fv=0.012502865999830526, second_stage_fl=0.9874971340001695, second_stage_vapour_composition={'CO2': 0.0038012155485513564, 'N2': 0.025570185277730216, 'C1': 0.8251127916903748, 'C2': 0.09395805143439408, 'C3': 0.03380572668537247, 'iC4': 0.004102989233803636, 'nC4': 0.008417693217665315, 'iC5': 0.0018818632582493684, 'nC5': 0.001305014494617525, 'C6': 0.0009287939176910025, 'C7': 0.0006107670070087145, 'C8': 0.00035494415453287613, 'C9': 0.00010026869675784982, 'C10': 3.0768112026755725e-05, 'C11': 1.0225580747369058e-05, 'C12': 3.7283825322266735e-06, 'C13': 1.3404638291450981e-06, 'C14': 4.3664030292113357e-07, 'C15': 1.3409004320299867e-07, 'C16': 4.347401062771828e-08, 'C17': 1.1684745259864503e-08, 'C18': 4.284754004045719e-09, 'C19': 1.7436735673629929e-09, 'C20': 6.353816267628642e-10, 'C21': 1.8661634799232284e-10, 'C22': 7.234358274203964e-11, 'C23': 2.1374762173331263e-11, 'C24': 7.261136077096928e-12, 'C25': 2.4583340649819352e-12, 'C26': 7.657884688197302e-13, 'C27': 2.4898429445408445e-13, 'C28': 7.757105570394603e-14, 'C29': 3.291717530314739e-14, 'C30': 1.3080123430694072e-14, 'C31': 4.108858946204685e-15, 'C32': 1.1840367722974734e-15, 'C33': 7.397689698879801e-16, 'C34': 2.109432722765388e-16, 'C35': 5.99228178945276e-17, 'C36': 5.36345817425928e-16}, second_stage_liquid_composition={'CO2': 0.0004773105872758789, 'N2': 0.00025638128170550254, 'C1': 0.023645879402451744, 'C2': 0.015950524043998646, 'C3': 0.02098802522386607, 'iC4': 0.006506839805126429, 'nC4': 0.01922755225965672, 'iC5': 0.011013624259116297, 'nC5': 0.010214678419983863, 'C6': 0.019208973411521512, 'C7': 0.03940704380193838, 'C8': 0.06256307226325301, 'C9': 0.05244245600237506, 'C10': 0.046529058343376554, 'C11': 0.04257480174053251, 'C12': 0.044246674062866496, 'C13': 0.04434676362290178, 'C14': 0.041850226889156045, 'C15': 0.04049551068163525, 'C16': 0.037778813578453765, 'C17': 0.03062879452403524, 'C18': 0.027399934368474276, 'C19': 0.026148680019320487, 'C20': 0.0250080804028064, 'C21': 0.0200952723453165, 'C22': 0.020386097012800062, 'C23': 0.016369879862081185, 'C24': 0.014561092551601632, 'C25': 0.01369287464187755, 'C26': 0.012084117924206128, 'C27': 0.011598937326816886, 'C28': 0.010227096280510222, 'C29': 0.011352091057953324, 'C30': 0.010776116430425883, 'C31': 0.009079402995622097, 'C32': 0.0065910791121351, 'C33': 0.010658367922831057, 'C34': 0.007352897769737021, 'C35': 0.005712930603652556, 'C36': 0.1305490471666055}, second_stage_vapour_z=0.9836876436894707, second_stage_liquid_z=0.06422693021834375, second_stage_k_values={'CO2': 7.963819889782386, 'N2': 99.73499277182769, 'C1': 34.89456990146123, 'C2': 5.890593385848386, 'C3': 1.6107149827002798, 'iC4': 0.6305655827843012, 'nC4': 0.43779328247243054, 'iC5': 0.17086684764024843, 'nC5': 0.1277587449120681, 'C6': 0.048352085131937006, 'C7': 0.015498929837986775, 'C8': 0.005673381144700526, 'C9': 0.001911975609100168, 'C10': 0.0006612665960203252, 'C11': 0.0002401791747543006, 'C12': 8.426356582032174e-05, 'C13': 3.0226869327908496e-05, 'C14': 1.0433403481362557e-05, 'C15': 3.311232305654282e-06, 'C16': 1.15075108267859e-06, 'C17': 3.8149543400068094e-07, 'C18': 1.5637825793391887e-07, 'C19': 6.6683043506389e-08, 'C20': 2.540705310158719e-08, 'C21': 9.286579688272628e-09, 'C22': 3.548672543676036e-09, 'C23': 1.3057372658453819e-09, 'C24': 4.986669819840028e-10, 'C25': 1.7953381808254484e-10, 'C26': 6.337148260410072e-11, 'C27': 2.1466129821947538e-11, 'C28': 7.584856304890098e-12, 'C29': 2.8996574406514716e-12, 'C30': 1.2138068027701455e-12, 'C31': 4.5254725979074763e-13, 'C32': 1.7964232444388288e-13, 'C33': 6.940734033991613e-14, 'C34': 2.868845438661433e-14, 'C35': 1.0488980534126568e-14, 'C36': 4.108385538359758e-15}, second_stage_vapour_mw=19.58998442364195, second_stage_liquid_mw=235.00667697505497, second_stage_vapour_volume=59.92015053429062, second_stage_liquid_volume=309.00044996753184, second_stage_vapour_density=0.00408762241088489, second_stage_liquid_density=0.7510293917311608, third_stage_pressure=0.1, third_stage_temperature=293.14, third_stage_fv=0.03711798658042653, third_stage_fl=0.9628820134195735, third_stage_vapour_composition={'CO2': 0.007697398087036942, 'N2': 0.006564354214176653, 'C1': 0.5534900897426475, 'C2': 0.22451479471488037, 'C3': 0.12822776541277528, 'iC4': 0.01781820192989003, 'nC4': 0.03764697117133619, 'iC5': 0.008687715902694319, 'nC5': 0.006024834049125037, 'C6': 0.004289241674022561, 'C7': 0.0027920351064096597, 'C8': 0.0015988479979697028, 'C9': 0.000443740874298533, 'C10': 0.00013369441446747608, 'C11': 4.3642310765016795e-05, 'C12': 1.5619421358948865e-05, 'C13': 5.517805415692901e-06, 'C14': 1.7645642372197663e-06, 'C15': 5.311458222726026e-07, 'C16': 1.6901370992577393e-07, 'C17': 4.4564136875066176e-08, 'C18': 1.6087743809185516e-08, 'C19': 6.450906471834146e-09, 'C20': 2.311712012275194e-09, 'C21': 6.673259580402999e-10, 'C22': 2.5451174231144525e-10, 'C23': 7.394469836616057e-11, 'C24': 2.4715475728224752e-11, 'C25': 8.223962828235179e-12, 'C26': 2.517994312911242e-12, 'C27': 8.042531640989858e-13, 'C28': 2.463135604513315e-13, 'C29': 1.0290333029494798e-13, 'C30': 4.0323337907852316e-14, 'C31': 1.2471305797234394e-14, 'C32': 3.541698285035271e-15, 'C33': 2.1799961646851765e-15, 'C34': 6.130165725916036e-16, 'C35': 1.714446370209173e-16, 'C36': 1.5123181528013145e-15}, third_stage_liquid_composition={'CO2': 0.00019898457516783226, 'N2': 1.3216229919316211e-05, 'C1': 0.0032209986641775924, 'C2': 0.007910612931291113, 'C3': 0.016854057425377492, 'iC4': 0.006070799894003517, 'nC4': 0.01851750499067211, 'iC5': 0.01110328533280732, 'nC5': 0.010376192068555723, 'C6': 0.019784111792650185, 'C7': 0.04081850998622842, 'C8': 0.06491317251087168, 'C9': 0.0544469462549958, 'C10': 0.04831754589606371, 'C11': 0.04421432868460493, 'C12': 0.04595172999883836, 'C13': 0.04605606730110401, 'C14': 0.04346343665041364, 'C15': 0.042056545248733326, 'C16': 0.03923513657798811, 'C17': 0.03180949736627574, 'C18': 0.028456169488535417, 'C19': 0.02715668110468858, 'C20': 0.025972112853356516, 'C21': 0.020869921797770915, 'C22': 0.021171957435318616, 'C23': 0.017000919771261083, 'C24': 0.01512240580647266, 'C25': 0.01422071910237839, 'C26': 0.012549946676433596, 'C27': 0.012046062928930033, 'C28': 0.010621338998929506, 'C29': 0.011789701022281801, 'C30': 0.011191523239855889, 'C31': 0.009429403466970056, 'C32': 0.006845157579304499, 'C33': 0.011069235663649911, 'C34': 0.007636343463955631, 'C35': 0.005933157462733862, 'C36': 0.13558156175643404}, third_stage_vapour_z=0.9936309786924046, third_stage_liquid_z=0.0132482622896976, third_stage_k_values={'CO2': 38.68339081330612, 'N2': 496.6888631819658, 'C1': 171.8380376553085, 'C2': 28.381466349692413, 'C3': 7.608124392628457, 'iC4': 2.9350665877638473, 'nC4': 2.033047712977544, 'iC5': 0.7824455233105085, 'nC5': 0.5806401818045416, 'C6': 0.21680233709637742, 'C7': 0.06840120100786756, 'C8': 0.02463056319889352, 'C9': 0.00814996808490095, 'C10': 0.0027669951357849856, 'C11': 0.0009870626121303678, 'C12': 0.00033990932135403204, 'C13': 0.00011980626525531921, 'C14': 4.059881990953822e-05, 'C15': 1.2629326045001279e-05, 'C16': 4.307713051790288e-06, 'C17': 1.400969539440533e-06, 'C18': 5.653517004692791e-07, 'C19': 2.3754399320616546e-07, 'C20': 8.900746833064986e-08, 'C21': 3.197548915164484e-08, 'C22': 1.2021172019119692e-08, 'C23': 4.349452815556435e-09, 'C24': 1.6343613605214912e-09, 'C25': 5.7830850669568e-10, 'C26': 2.006378495328235e-10, 'C27': 6.676481509717814e-11, 'C28': 2.3190443358992373e-11, 'C29': 8.728239172517359e-12, 'C30': 3.6030249898647003e-12, 'C31': 1.3225975366225145e-12, 'C32': 5.174020092310461e-13, 'C33': 1.9694188749129546e-13, 'C34': 8.027619180372232e-14, 'C35': 2.8896020053025796e-14, 'C36': 1.1154305446917065e-14}, third_stage_vapour_mw=26.984047094365632, third_stage_liquid_mw=243.02570846253164, third_stage_vapour_volume=898.4328870875304, third_stage_liquid_volume=310.74782614607557, third_stage_vapour_density=0.0011148228346595246, third_stage_liquid_density=0.7530385212320687)

## Начинаем играть корреляциями

In [86]:
prr_base_comp = Composition(przlm_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'rizari_daubert',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})

In [62]:
prr_kesler_comp = Composition(przlm_dict, c6_plus_correlations= {'critical_temperature': 'pedersen',
                                                    'critical_pressure': 'pedersen',
                                                    'acentric_factor': 'rizari_al_sahhaf',
                                                    'critical_volume': 'hall_yarborough',
                                                    'k_watson': 'k_watson',
                                                    'shift_parameter': 'jhaveri_youngren'})
prr_kesler_comp.COMPOSITION_PROPERTIES.describe()

,molar_mass,gamma,Tb,critical_pressure,critical_temperature,acentric_factor,shift_parameter,critical_volume,c5_plus_flag
count,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000
mean,235.324025,0.777948,513.599500,2.317859,646.040657,0.707354,0.108961,15.502312,0.775000
std,151.968692,0.157837,200.195077,1.312239,201.921390,0.429286,0.145697,10.282038,0.422902
min,16.043000,0.330000,77.390000,1.311351,126.190000,0.013000,-0.192700,0.090100,0.000000
25%,93.544500,0.717750,358.050000,1.407845,527.029460,0.293227,-0.020308,6.078818,1.000000
50%,229.500000,0.847000,564.650000,1.675149,697.472980,0.724813,0.150584,14.792799,1.000000
75%,362.750000,0.893000,683.900000,3.077022,805.346890,1.075208,0.236398,24.015258,1.000000
max,500.000000,0.922000,766.150000,7.387000,898.796296,1.403862,0.291305,33.864255,1.000000

In [74]:
model_base = CompositionalModel(prr_base_comp)
model_kesler = CompositionalModel(prr_kesler_comp)

In [77]:
model_kesler.experiments.SEPARATORTEST_MOD.calculate(150, 60, [0.76,0.3,0.101], [55, 58.3, 20])

GVOL BY STAGES STC: [0, 0, 7417.573431956575, 378.4647704996596, 135.6766868804984, 0]
GVOL BY STAGES ACC STC: [0, 0, 7417.573431956575, 7796.038202456235, 7931.714889336733, 7931.714889336733]

DLEResults(index=['150_333.14', '10.110507365444207_333.14', '0.76_331.44', '0.3_328.14', '0.101_293.14', 'STC_0.101325_293.14'], pressure_arr=[150, 10.110507365444207, 0.76, 0.3, 0.101, 0.101325], temperature_arr=[333.14, 333.14, 331.44, 328.14, 293.14, 293.14], liquid_volume_arr=[193.23608340919742, 205.1059513908803, 188.85077045405106, 272.1090088192207, 273.91756533559925, 278.5352288129547], gas_volume_arr=[193.23608340919742, 0.0003731513992303443, 1104.4253404904598, 206.38992248193895, 202.00671754930397, 278.5352288129547], liquid_density_arr=[0.8862718200375644, 0.8349845183295471, 0.872752924722444, 0.8762002319020133, 0.8900800380634968, 0.8827606653095227], gas_density_arr=[0.8862718200375644, 0.07656444598562377, 0.005831536442797236, 0.0027433143928842015, 0.0010703278967069284, 0.8827606653095227], fl_arr=[None, 0.9999984535689777, 0.6896578307112406, 0.9770400612775818, 0.9915756165954561, None], fv_arr=[None, 1.5464310223478606e-06, 0.31034216928875935, 0.022959938722418194, 0.008424383404543878, None], liquid_z=[10.470120507937786, 0.7490728879471852, 0.07556013712517705, 0.030640200737368506, 0.011453528759707933, 0.011585656208868478], gas_z=[10.470103186515965, 0.8812510873357596, 0.981981304295959, 0.9889602145457154, 0.9941981583289906, 0.994173630261646], liquid_compositions=[{'CO2': 0.0012270038248028007, 'N2': 0.01211602643665037, 'C1': 0.26600467703893577, 'C2': 0.03283009458664491, 'C3': 0.022251065546479744, 'iC4': 0.005487015810103155, 'nC4': 0.015398046948826249, 'iC5': 0.008177024778192982, 'nC5': 0.007488022350228696, 'C6': 0.013746041511577075, 'C7': 0.02791408659110318, 'C8': 0.044180133159228994, 'C9': 0.03698910581013707, 'C10': 0.03280508909947226, 'C11': 0.030013077148794042, 'C12': 0.03119007655696037, 'C13': 0.031260074246813783, 'C14': 0.02950006864818996, 'C15': 0.028545065647582173, 'C16': 0.026630060378788147, 'C17': 0.021590049747984102, 'C18': 0.019314044866918546, 'C19': 0.01843204381190283, 'C20': 0.017628043220467394, 'C21': 0.014165036049357704, 'C22': 0.01437003831830997, 'C23': 0.011539032410407336, 'C24': 0.010264030239961572, 'C25': 0.009652029742992093, 'C26': 0.008518027768466257, 'C27': 0.008176028319631832, 'C28': 0.007209026329434475, 'C29': 0.008002030857438374, 'C30': 0.007596030951838129, 'C31': 0.006400027737956136, 'C32': 0.004646021278716516, 'C33': 0.007513036351990907, 'C34': 0.005183026338011742, 'C35': 0.004027021598544937, 'C36': 0.09202351794015722}, {'CO2': 0.0012270035006256268, 'N2': 0.01211591569868876, 'C1': 0.266003756422193, 'C2': 0.03283009409827802, 'C3': 0.022251083940192474, 'iC4': 0.0054870220091861694, 'nC4': 0.015398065923609063, 'iC5': 0.008177035974092478, 'nC5': 0.007488032729059954, 'C6': 0.013746061602165684, 'C7': 0.027914128330164597, 'C8': 0.04418020002734945, 'C9': 0.036989162291243965, 'C10': 0.03280513943145027, 'C11': 0.030013123331335736, 'C12': 0.031190124648059463, 'C13': 0.03126012250412713, 'C14': 0.0295001142234717, 'C15': 0.028545109767600572, 'C16': 0.02663010154893986, 'C17': 0.02159008313057371, 'C18': 0.01931407473230031, 'C19': 0.018432072314404815, 'C20': 0.017628070480257642, 'C21': 0.014165057954323497, 'C22': 0.014370060540446624, 'C23': 0.011539050254678187, 'C24': 0.010264046112565036, 'C25': 0.009652044669195978, 'C26': 0.008518040941021253, 'C27': 0.008176040963311669, 'C28': 0.007209037477712116, 'C29': 0.008002043232045421, 'C30': 0.007596042698593813, 'C31': 0.006400037635172722, 'C32': 0.004646028463479008, 'C33': 0.0075130479704013185, 'C34': 0.0051830343532168425, 'C35': 0.0040270278260656905, 'C36': 0.09202366024840017}, {'CO2': 0.0003332319818935236, 'N2': 0.0004355427787606038, 'C1': 0.02384400398964038, 'C2': 0.011002278400644062, 'C3': 0.015167725541165057, 'iC4': 0.005221438721922485, 'nC4': 0.01617725538144475, 'iC5': 0.010090335851191548, 'nC5': 0.009538140386718042, 'C6': 0.018789221641551453, 'C7': 0.039342162725020204, 'C8': 0.06311083824238589, 'C9': 0.053268679370240934, 'C10': 0.04740695625423979, 'C11': 0.043445241603993295, 'C12': 0.045190070031645685, 'C13': 0.045310459170273765, 'C14': 0.042768186914126226, 'C15': 0.041387549996397224, 'C16': 0.03861246821398487, 'C17': 0.03130514827802215, 'C18': 0.02800516008885662, 'C19': 0.026726335898172124, 'C20': 0.02556057295460982, 'C21': 0.020539245454003534, 'C22': 0.020836503440244195, 'C23': 0.016731556945595773, 'C24': 0.014882808936166602, 'C25': 0.013995410607410809, 'C26': 0.012351111679226983, 'C27': 0.011855213672620931, 'C28': 0.010453064041255133, 'C29': 0.01160291795839856, 'C30': 0.01101421945673718, 'C31': 0.00928001880037051, 'C32': 0.006736715305024299, 'C33': 0.010893877566204226, 'C34': 0.007515370843910126, 'C35': 0.005839167840533666, 'C36': 0.13343379303539496}, {'CO2': 0.00022187493729519415, 'N2': 7.224254566959168e-05, 'C1': 0.00827217842911815, 'C2': 0.007989513832171792, 'C3': 0.013688210389594406, 'iC4': 0.005037582816444499, 'nC4': 0.015861997236900953, 'iC5': 0.010127643372113573, 'nC5': 0.009614108736034634, 'C6': 0.019104081694258052, 'C7': 0.04014386572426412, 'C8': 0.06449305956284675, 'C9': 0.0544827197916194, 'C10': 0.048504843599476384, 'C11': 0.04445894644848032, 'C12': 0.04624862485772327, 'C13': 0.04637369147124414, 'C14': 0.04377260086929569, 'C15': 0.04235989925640428, 'C16': 0.039519753694822746, 'C17': 0.03204077409072942, 'C18': 0.02866325565203926, 'C19': 0.027354385857601454, 'C20': 0.02616123090889451, 'C21': 0.021021906453945204, 'C22': 0.021326150258509872, 'C23': 0.017124739823947105, 'C24': 0.01523254724995308, 'C25': 0.014324295541098086, 'C26': 0.012641356443621537, 'C27': 0.012133805092292699, 'C28': 0.010698705667198983, 'C29': 0.011875580560104232, 'C30': 0.011273047946720075, 'C31': 0.00949809446729144, 'C32': 0.006895024648434441, 'C33': 0.011149878083765483, 'C34': 0.0076919781918480205, 'C35': 0.005976385280351795, 'C36': 0.13656941851587315}, {'CO2': 0.0001678034865262154, 'N2': 1.1689100266209306e-05, 'C1': 0.0031118791731821202, 'C2': 0.006406801883093535, 'C3': 0.012930327476774533, 'iC4': 0.00494996575978904, 'nC4': 0.01571857390858999, 'iC5': 0.010144145243952903, 'nC5': 0.00964730016604611, 'C6': 0.01923013143859738, 'C7': 0.04045559650155772, 'C8': 0.0650201307197326, 'C9': 0.05493905530928287, 'C10': 0.04891455141080892, 'C11': 0.044835754225569284, 'C12': 0.04664119424507246, 'C13': 0.046767544675588295, 'C14': 0.04414444630795362, 'C15': 0.04271977321574631, 'C16': 0.039855507641579954, 'C17': 0.03231298999150248, 'C18': 0.028906777067033564, 'C19': 0.027586787392527016, 'C20': 0.02638349553751322, 'C21': 0.021200507646120612, 'C22': 0.021507336301240097, 'C23': 0.017270230869049483, 'C24': 0.015361962309912866, 'C25': 0.014445994134226932, 'C26': 0.012748756859302598, 'C27': 0.012236893373744487, 'C28': 0.010789601406224715, 'C29': 0.01197647497714578, 'C30': 0.011368823272828638, 'C31': 0.009578789865671353, 'C32': 0.006953604478605756, 'C33': 0.011244606964064157, 'C34': 0.007757328904736672, 'C35': 0.006027160390320535, 'C36': 0.13772970636851678}, {'CO2': 0.00016729069111105473, 'N2': 1.1406375532203337e-05, 'C1': 0.0030606226442168507, 'C2': 0.006346885187175403, 'C3': 0.012831808996248114, 'iC4': 0.004902066459666338, 'nC4': 0.015616565133113356, 'iC5': 0.010063877927641202, 'nC5': 0.009581202879299406, 'C6': 0.019077103004141043, 'C7': 0.040280835448751225, 'C8': 0.06461451815590502, 'C9': 0.05441196471704701, 'C10': 0.048291660710621305, 'C11': 0.04412389662979426, 'C12': 0.04578805354367779, 'C13': 0.04583700618943992, 'C14': 0.043227013847377864, 'C15': 0.04181476869897297, 'C16': 0.03899073972302215, 'C17': 0.031644881190542644, 'C18': 0.028326668878288865, 'C19': 0.02707083044981329, 'C20': 0.025938462292525076, 'C21': 0.02089172957770497, 'C22': 0.021256867883140608, 'C23': 0.017127437268751388, 'C24': 0.015285337228552003, 'C25': 0.014420972682812339, 'C26': 0.012780803893164813, 'C27': 0.012327065531213125, 'C28': 0.010917805058923442, 'C29': 0.012177298737155524, 'C30': 0.011619105367882783, 'C31': 0.009849256200365725, 'C32': 0.00719127793889761, 'C33': 0.011699481297908909, 'C34': 0.008117227663245654, 'C35': 0.006348362116193038, 'C36': 0.1459698417801636}], gas_compositions=[{'CO2': 0.0012270031978506195, 'N2': 0.012116062458472413, 'C1': 0.26600510777284136, 'C2': 0.03283010629256869, 'C3': 0.022251068490416887, 'iC4': 0.005487017742331707, 'nC4': 0.015398042109870027, 'iC5': 0.008177022263758287, 'nC5': 0.007488022518217524, 'C6': 0.013746038275997057, 'C7': 0.027914075327800273, 'C8': 0.04418013009416098, 'C9': 0.036989124680201844, 'C10': 0.032805123737483795, 'C11': 0.03001312532254477, 'C12': 0.031190140325878135, 'C13': 0.03126014762082342, 'C14': 0.02950014338284158, 'C15': 0.028545141070475587, 'C16': 0.0266301341591964, 'C17': 0.021590106734081956, 'C18': 0.019314094609616136, 'C19': 0.018432087670823754, 'C20': 0.017628080333802178, 'C21': 0.014165061047489654, 'C22': 0.01437005724557449, 'C23': 0.011539041549486975, 'C24': 0.01026403316297236, 'C25': 0.009652027677600799, 'C26': 0.008518020325905899, 'C27': 0.008176015012357934, 'C28': 0.007209009568489711, 'C29': 0.008002006213354104, 'C30': 0.007596001410650878, 'C31': 0.006399996694316201, 'C32': 0.004645994507703709, 'C33': 0.007512985859245093, 'C34': 0.00518298683622807, 'C35': 0.004026986697247488, 'C36': 0.09202262999932113}, {'CO2': 0.0014366327495019173, 'N2': 0.08372464574300459, 'C1': 0.8613207989879271, 'C2': 0.03314589666899139, 'C3': 0.010356785089292461, 'iC4': 0.0014783834570267081, 'nC4': 0.003128017960950404, 'iC5': 0.0009372048183680286, 'nC5': 0.0007765589494721615, 'C6': 0.0007544775493433651, 'C7': 0.0009235540250844553, 'C8': 0.0009399135305330268, 'C9': 0.0004656406589081105, 'C10': 0.0002579535029694497, 'C11': 0.00014917141460842103, 'C12': 9.200362165361013e-05, 'C13': 5.4518988680448554e-05, 'C14': 2.8847105067417528e-05, 'C15': 1.4889045598829989e-05, 'C16': 7.41284542493416e-06, 'C17': 3.2233696352188284e-06, 'C18': 1.6182870237810604e-06, 'C19': 9.224131770408982e-07, 'C20': 5.204282026631994e-07, 'C21': 2.0644984775788567e-07, 'C22': 1.1042181295336762e-07, 'C23': 4.81309776021177e-08, 'C24': 2.3188317548208095e-08, 'C25': 1.1264637680104618e-08, 'C26': 5.021213704728856e-09, 'C27': 2.293679893051256e-09, 'C28': 1.0060815914918109e-09, 'C29': 5.493115522165752e-10, 'C30': 2.5372908514696696e-10, 'C31': 1.0207296095091567e-10, 'C32': 3.5343841134139206e-11, 'C33': 2.7005929288288446e-11, 'C34': 8.790566412019666e-12, 'C35': 3.1696468393310836e-12, 'C36': 3.3566350617893914e-11}, {'CO2': 0.003213187099757281, 'N2': 0.03807262235030957, 'C1': 0.804143223356229, 'C2': 0.0813369536645917, 'C3': 0.037992075887304036, 'iC4': 0.006077214422248185, 'nC4': 0.013666512289001245, 'iC5': 0.00392520566123392, 'nC5': 0.002932181350095611, 'C6': 0.0025389000982572896, 'C7': 0.002518180921173437, 'C8': 0.0021115926083762225, 'C9': 0.0008120083470722591, 'C10': 0.0003562545843575089, 'C11': 0.0001636008800104094, 'C12': 7.874850008835618e-05, 'C13': 3.676433741517143e-05, 'C14': 1.5142037684765424e-05, 'C15': 5.99924475785964e-06, 'C16': 2.2893507445293754e-06, 'C17': 7.813281056192194e-07, 'C18': 3.118386993990839e-07, 'C19': 1.465350699073939e-07, 'C20': 6.826221868171994e-08, 'C21': 2.091262597103397e-08, 'C22': 8.952184996090624e-09, 'C23': 3.1808665152950535e-09, 'C24': 1.2462325403327076e-09, 'C25': 4.826155424537134e-10, 'C26': 1.7223989685755325e-10, 'C27': 6.197571508438564e-11, 'C28': 2.1700005668586414e-11, 'C29': 9.459793847228439e-12, 'C30': 3.489407057713682e-12, 'C31': 1.1267114800366036e-12, 'C32': 3.117079376428399e-13, 'C33': 1.903166619667494e-13, 'C34': 4.923436605169459e-14, 'C35': 1.418540520165228e-14, 'C36': 1.1933724041293374e-13}, {'CO2': 0.0050719333779825765, 'N2': 0.015895465659775034, 'C1': 0.6864893874897775, 'C2': 0.13920783304879025, 'C3': 0.07812719559150375, 'iC4': 0.013045265576436677, 'nC4': 0.02959278930717663, 'iC5': 0.008502747009232679, 'nC5': 0.006305373889873353, 'C6': 0.005390628164908307, 'C7': 0.0052263945177260995, 'C8': 0.004291621868622724, 'C9': 0.0016062536975234775, 'C10': 0.0006873228948322284, 'C11': 0.0003079207535710823, 'C12': 0.00014419753867261459, 'C13': 6.554083440331378e-05, 'C14': 2.6231712449835957e-05, 'C15': 1.0079783338651548e-05, 'C16': 3.730076170974456e-06, 'C17': 1.2368079491978774e-06, 'C18': 4.804095220813187e-07, 'C19': 2.205428613971922e-07, 'C20': 1.0036118086589302e-07, 'C21': 2.97940394128748e-08, 'C22': 1.240660068123092e-08, 'C23': 4.296346350383304e-09, 'C24': 1.6401953628325803e-09, 'C25': 6.175166304461981e-10, 'C26': 2.142533793501695e-10, 'C27': 7.47841386210857e-11, 'C28': 2.5445471597008075e-11, 'C29': 1.0777921107652153e-11, 'C30': 3.862337205660896e-12, 'C31': 1.2117286476626289e-12, 'C32': 3.2560241965833794e-13, 'C33': 1.9306988530629484e-13, 'C34': 4.848713602253627e-14, 'C35': 1.3564311236759971e-14, 'C36': 1.107485580004436e-13}, {'CO2': 0.006586249581918088, 'N2': 0.007199567725391644, 'C1': 0.6156551370159709, 'C2': 0.19427953666681494, 'C3': 0.10289334036755661, 'iC4': 0.01535037757013022, 'nC4': 0.032743360343832656, 'iC5': 0.008185322734707796, 'nC5': 0.00570737620750764, 'C6': 0.004267642400961711, 'C7': 0.003452202624035044, 'C8': 0.002455177111191202, 'C9': 0.000770637782447682, 'C10': 0.0002809848151157657, 'C11': 0.00010752202216244526, 'C12': 4.201083926379463e-05, 'C13': 1.596827751995959e-05, 'C14': 5.258808799585666e-06, 'C15': 1.636818021316275e-06, 'C16': 4.902908606239747e-07, 'C17': 1.3245628655624546e-07, 'C18': 4.249664865134668e-08, 'C19': 1.6496011283509393e-08, 'C20': 6.331783232223193e-09, 'C21': 1.4964270511816325e-09, 'C22': 5.082727496370656e-10, 'C23': 1.452314116767047e-10, 'C24': 4.570920563823198e-11, 'C25': 1.3968079466768933e-11, 'C26': 3.918624007683886e-12, 'C27': 1.0868946996438407e-12, 'C28': 2.979749135941132e-13, 'C29': 1.0147310849123889e-13, 'C30': 2.917551647130517e-14, 'C31': 7.32401361514593e-15, 'C32': 1.5732237930966252e-15, 'C33': 7.444323969352783e-16, 'C34': 1.490050257883931e-16, 'C35': 3.315439695487529e-17, 'C36': 2.1501250047588311e-16}, {'CO2': 0.006586240336621782, 'N2': 0.0071993815660024016, 'C1': 0.6156459631980779, 'C2': 0.19428127791813912, 'C3': 0.10289645340995358, 'iC4': 0.015351106896865594, 'nC4': 0.032744985513901516, 'iC5': 0.00818585551218237, 'nC5': 0.0057077960666898015, 'C6': 0.004268014433136908, 'C7': 0.0034525606002292824, 'C8': 0.002455470439790902, 'C9': 0.0007707454480890913, 'C10': 0.00028102923430154406, 'C11': 0.00010754096175717198, 'C12': 4.201904159236444e-05, 'C13': 1.597168419180948e-05, 'C14': 5.260029291540855e-06, 'C15': 1.6372300076549008e-06, 'C16': 4.904239553979057e-07, 'C17': 1.3249456360213817e-07, 'C18': 4.250963939831311e-08, 'C19': 1.6501281336686236e-08, 'C20': 6.333891689229843e-09, 'C21': 1.4969527325064038e-09, 'C22': 5.084591622860916e-10, 'C23': 1.4528670495110838e-10, 'C24': 4.572725630297552e-11, 'C25': 1.3973814140899137e-11, 'C26': 3.92029167473005e-12, 'C27': 1.0873746755236331e-12, 'C28': 2.981110178540975e-13, 'C29': 1.0152098295931803e-13, 'C30': 2.9189716265448445e-14, 'C31': 7.327682497234758e-15, 'C32': 1.5740349565297586e-15, 'C33': 7.448270727823148e-16, 'C34': 1.4908626954887878e-16, 'C35': 3.3172951219852624e-17, 'C36': 2.1513604060588997e-16}], liquid_viscosity=None, gas_viscosity=None, bo=array([1.03833354, 1.10211502, 1.01476796, 1.00838082, 0.99177673,
       1.        ]), rs=array([42.62022642, 42.62022642,  2.76268444,  0.72904425,  0.        ,
        0.        ]))

In [85]:
model_base.saturation_pressure(58)

SATURATION PRESSURE CALCULATION
=====
CALCULATED SATURATION PRESSURE: 87.05150362482529 bar
TEMPERATURE: 58 C

In [78]:
dleresview = DLEResultsViewer()
dleresview.view(model_kesler.experiments.SEPARATORTEST_MOD.result)

,Index,Pressure,Temperature,Fl,Fv,Liquid Z,Gas Z,Liquid volume,Gas volume,Liquid density,Gas density,Bo,Rs,Liquid viscosity,Gas viscosity
0,150_333.14,150.000000,333.14,NaN,NaN,10.470121,10.470103,193.236083,193.236083,0.886272,0.886272,1.038334,42.620226,None,None
1,10.110507365444207_333.14,10.110507,333.14,0.999998,0.000002,0.749073,0.881251,205.105951,0.000373,0.834985,0.076564,1.102115,42.620226,None,None
2,0.76_331.44,0.760000,331.44,0.689658,0.310342,0.075560,0.981981,188.850770,1104.425340,0.872753,0.005832,1.014768,2.762684,None,None
3,0.3_328.14,0.300000,328.14,0.977040,0.022960,0.030640,0.988960,272.109009,206.389922,0.876200,0.002743,1.008381,0.729044,None,None
4,0.101_293.14,0.101000,293.14,0.991576,0.008424,0.011454,0.994198,273.917565,202.006718,0.890080,0.001070,0.991777,0.000000,None,None
5,STC_0.101325_293.14,0.101325,293.14,NaN,NaN,0.011586,0.994174,278.535229,278.535229,0.882761,0.882761,1.000000,0.000000,None,None