In [1]:
from calculations.Composition.Composition import Composition
from calculations.Utils.Conditions import Conditions
from calculations.CompositionalModel.CompositionalModel import CompositionalModel
from calculations.EOS.PenelouxVolumeCorrection import PenelouxVolumeCorrection
from calculations.Utils.ResultsViewer import FlashResultsViewer, DLEResultsViewer, SeparatorTestResultsViewer, StandardSeparationResultsViewer
from calculations.Utils.CompositionLoader import CompositionExcelLoader

# KRSNLN

In [47]:
excel_loader = CompositionExcelLoader(r'C:\Users\user\Desktop\PVT_TSU\diss\krsnln.xlsx')
krsnln_dict = excel_loader.load(header=True, sheet='to_model')

In [48]:
krsnln_dict

{'N2': 0.00261026114225388,
 'CO2': 0.0148314833641052,
 'C1': 0.3894189453125,
 'C2': 0.10339034080505399,
 'C3': 0.0787178707122803,
 'iC4': 0.00978097677230835,
 'nC4': 0.030433042049408,
 'iC5': 0.00874087512493134,
 'nC5': 0.0172917282581329,
 'C6': 0.022392239570617697,
 'C7': 0.0320032024383545,
 'C8': 0.0401340103149414,
 'C9': 0.0294429445266724,
 'C10': 0.0253425335884094,
 'C11': 0.020472047328949,
 'C12': 0.017351735830307,
 'C13': 0.0167916786670685,
 'C14': 0.0147614753246307,
 'C15': 0.0121512150764465,
 'C16': 0.010651066303253201,
 'C17': 0.009040904045104981,
 'C18': 0.00857085704803467,
 'C19': 0.00800080060958862,
 'C20': 0.00688068866729736,
 'C21': 0.00569056928157806,
 'C22': 0.0051305133104324295,
 'C23': 0.00486048579216003,
 'C24': 0.0044504451751709,
 'C25': 0.003910391032695771,
 'C26': 0.0036303630471229598,
 'C27': 0.00348034799098969,
 'C28': 0.0027502751350402797,
 'C29': 0.00289028912782669,
 'C30': 0.00266026616096497,
 'C31': 0.00241024121642113,
 'C32': 0.0021102112531662,
 'C33': 0.00183018296957016,
 'C34': 0.00170017004013062,
 'C35': 0.00176017612218857,
 'C36': 0.021532154083252}

In [49]:
krsnln_base_composition = Composition(zi = krsnln_dict)

In [50]:
krsnln_base_composition.COMPOSITION_PROPERTIES

,molar_mass,gamma,Tb,critical_pressure,critical_temperature,acentric_factor,shift_parameter,critical_volume,bip,c5_plus_flag
N2,28.013,0.4700,77.39,3.394000,126.190000,0.040000,-0.192700,0.090100,"{'CO2': 0, 'N2': 0, 'C1': 0.003, 'C2': 0.011, ...",0
CO2,44.010,0.5000,194.67,7.387000,304.690000,0.225000,-0.081700,1.505735,"{'CO2': 0, 'N2': 0, 'C1': 0.004, 'C2': 0.009, ...",0
C1,16.043,0.3300,111.67,4.604000,190.600000,0.013000,-0.159500,1.585828,"{'CO2': 0.004, 'N2': 0.003, 'C1': 0, 'C2': 0.0...",0
C2,30.070,0.4500,184.56,4.884000,305.420000,0.099000,-0.113400,2.370730,"{'CO2': 0.009, 'N2': 0.011, 'C1': 0.024, 'C2':...",0
C3,44.097,0.5077,231.11,4.246000,369.790000,0.152000,-0.086300,3.251740,"{'CO2': 0, 'N2': 0, 'C1': 0.004, 'C2': 0.009, ...",0
iC4,58.124,0.5613,261.44,3.648000,408.090000,0.185000,-0.084400,4.212855,"{'CO2': 0.008, 'N2': 0.01, 'C1': 0.023, 'C2': ...",0
nC4,58.124,0.5844,272.67,3.797000,425.190000,0.201000,-0.094000,4.084708,"{'CO2': 0.023, 'N2': 0.026, 'C1': 0.045, 'C2':...",0
iC5,72.151,0.6274,301.00,3.389000,460.390000,0.227000,-0.060800,4.901640,"{'CO2': 0.04, 'N2': 0.044, 'C1': 0.067, 'C2': ...",0
nC5,72.151,0.6301,309.22,3.370000,469.590000,0.251000,-0.039000,4.869612,"{'CO2': 0, 'N2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",0
C6,86.178,0.6900,337.05,3.104000,507.500000,0.252000,-0.008000,5.926800,"{'CO2': 0.05, 'N2': 0.054, 'C1': 0.042, 'C2': ...",1
C7,96.000,0.7270,365.05,3.133670,542.425284,0.314414,-0.039968,6.129490,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C8,107.000,0.7490,389.85,2.884574,570.548990,0.344631,-0.014077,6.781567,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C9,121.000,0.7680,415.35,2.640528,598.101705,0.379097,0.014491,7.657889,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C10,134.000,0.7820,438.95,2.423211,622.207636,0.415144,0.037589,8.488891,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C11,147.000,0.7930,460.35,2.242123,643.211673,0.450955,0.058077,9.338598,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C12,161.000,0.8040,481.45,2.087046,663.637780,0.487819,0.077782,10.255789,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C13,175.000,0.8150,500.35,1.970393,682.052389,0.520877,0.095481,11.166838,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C14,190.000,0.8260,519.55,1.863135,700.529768,0.555636,0.112604,12.144593,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C15,206.000,0.8360,539.15,1.758650,718.830726,0.593761,0.129122,13.201298,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C16,222.000,0.8430,556.15,1.668796,734.012976,0.630294,0.144131,14.292288,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C17,237.000,0.8510,573.15,1.591040,749.405879,0.666568,0.157037,15.293310,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C18,251.000,0.8560,586.15,1.531296,760.717895,0.696929,0.168206,16.260985,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C19,263.000,0.8610,598.15,1.481066,771.235587,0.725047,0.177185,17.079066,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C20,275.000,0.8660,611.15,1.428287,782.425100,0.757071,0.185673,17.895843,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C21,291.000,0.8710,624.15,1.378724,793.557111,0.790014,0.196305,19.011332,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C22,305.000,0.8760,636.15,1.336963,803.926774,0.820451,0.205034,19.975967,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C23,318.000,0.8810,648.15,1.297436,814.257812,0.851631,0.212708,20.863771,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C24,331.000,0.8850,659.15,1.261099,823.477599,0.882248,0.220005,21.769212,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C25,345.000,0.8880,670.15,1.223312,832.285994,0.916123,0.227478,22.770170,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C26,359.000,0.8920,681.15,1.190460,841.439317,0.948481,0.234587,23.751121,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C27,374.000,0.8960,692.15,1.159135,850.564319,0.981696,0.241834,24.807668,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C28,388.000,0.8990,702.15,1.130045,858.588807,1.014481,0.248281,25.810010,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C29,402.000,0.9020,711.15,1.105761,865.907445,1.043889,0.254448,26.812887,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C30,416.000,0.9050,719.15,1.085856,872.529981,1.069591,0.260356,27.816129,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C31,430.000,0.9090,728.15,1.065922,880.215310,1.097095,0.266024,28.794417,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C32,444.000,0.9120,736.15,1.047301,886.815764,1.123802,0.271469,29.797136,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C33,458.000,0.9150,744.15,1.029260,893.405930,1.151036,0.276706,30.799784,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C34,472.000,0.9170,751.15,1.012330,898.911351,1.177540,0.281750,31.829751,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C35,486.000,0.9200,759.15,0.995345,905.482109,1.205887,0.286612,32.832661,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1
C36,500.000,0.9220,766.15,0.979363,910.968559,1.233555,0.291305,33.864255,"{'N2': 0, 'CO2': 0, 'C1': 0, 'C2': 0, 'C3': 0,...",1

In [51]:
krsnln_model = CompositionalModel(krsnln_base_composition, eos= 'PREOS')

In [52]:
conds = Conditions(5,50)
krsnln_model.flash(conditions=conds)

In [53]:
krsnln_model.show_flashes

{'TwoPhaseFlash_5_50.0': TwoPhaseFlashResults(temperature=323.14, pressure=5, stable=False, EOS='PREOS', Fv=0.3588727438384467, Fl=0.6411272561615533, Ki={'N2': 10.376389873522633, 'CO2': 1.6050513381590847, 'C1': 4.679132133080466, 'C2': 1.2835747010328702, 'C3': 0.5186721633964178, 'iC4': 0.267687468209085, 'nC4': 0.20252683550231135, 'iC5': 0.10436991719240626, 'nC5': 0.08675809861422794, 'C6': 0.043310451425024564, 'C7': 0.019238853616124207, 'C8': 0.009567988496068977, 'C9': 0.004518497380560178, 'C10': 0.0021869881011768893, 'C11': 0.0010990711430797508, 'C12': 0.000539770200416727, 'C13': 0.00026837277005332754, 'C14': 0.0001300101923729881, 'C15': 5.963012757707283e-05, 'C16': 2.9204095395054493e-05, 'C17': 1.3808223076954614e-05, 'C18': 7.560301434298017e-06, 'C19': 4.244442115493492e-06, 'C20': 2.2093566237982026e-06, 'C21': 1.1173215535324595e-06, 'C22': 5.811455761155959e-07, 'C23': 2.943535162309254e-07, 'C24': 1.531021190415539e-07, 'C25': 7.671126769327221e-08, 'C26': 3.775605117279028e-08, 'C27': 1.8051053922131928e-08, 'C28': 8.895024475676115e-09, 'C29': 4.615408218619906e-09, 'C30': 2.542760130614381e-09, 'C31': 1.2899352560163077e-09, 'C32': 6.842940095723507e-10, 'C33': 3.5608023079786943e-10, 'C34': 1.944558852838686e-10, 'C35': 9.728472844407328e-11, 'C36': 5.113285459092223e-11}, liquid_composition={'N2': 0.0005980074564871759, 'CO2': 0.012185555333944293, 'C1': 0.16782838051281665, 'C2': 0.09384045730530036, 'C3': 0.09515440966821306, 'iC4': 0.013267864553185606, 'nC4': 0.042634736133760634, 'iC5': 0.012881074278014625, 'nC5': 0.025721695800684587, 'C6': 0.03409967390495434, 'C7': 0.04938525311754103, 'C8': 0.06226565623658098, 'C9': 0.045807854533490885, 'C10': 0.03947975638494296, 'C11': 0.03191169975482765, 'C12': 0.02705624293913286, 'C13': 0.026186933090734096, 'C14': 0.02302257627608139, 'C15': 0.018952258523403088, 'C16': 0.01661275837204574, 'C17': 0.01410146594125518, 'C18': 0.013368361264963496, 'C19': 0.012479241093144973, 'C20': 0.010732159788682437, 'C21': 0.008875875526853025, 'C22': 0.0080023296345325, 'C23': 0.007581154824739719, 'C24': 0.006941593499574002, 'C25': 0.006099242899448349, 'C26': 0.005662468621492961, 'C27': 0.005428482290178634, 'C28': 0.0042897491799250495, 'C29': 0.004508136399728044, 'C30': 0.004149357450665342, 'C31': 0.0037593803593860744, 'C32': 0.0032914078009907235, 'C33': 0.0028546329166579654, 'C34': 0.002651844892891509, 'C35': 0.0027454395444532218, 'C36': 0.033584836513657707}, vapour_composition={'N2': 0.006205158515784558, 'CO2': 0.01955844189495886, 'C1': 0.7852911681003758, 'C2': 0.12045123693043874, 'C3': 0.04935394351932108, 'iC4': 0.0035516410707833175, 'nC4': 0.00863467819164659, 'iC5': 0.0013443966557456207, 'nC5': 0.002231565420800966, 'C6': 0.0014768722702697024, 'C7': 0.0009501156555236137, 'C8': 0.0005957570825717923, 'C9': 0.00020698267071866022, 'C10': 8.634175745123257e-05, 'C11': 3.507322832715622e-05, 'C12': 1.46041536737794e-05, 'C13': 7.027859772761455e-06, 'C14': 2.993169570575133e-06, 'C15': 1.130125593624192e-06, 'C16': 4.851605802722139e-07, 'C17': 1.947161874289293e-07, 'C18': 1.0106884084571758e-07, 'C19': 5.296741646514157e-08, 'C20': 2.3711168316786263e-08, 'C21': 9.917207032624159e-09, 'C22': 4.650518465727297e-09, 'C23': 2.2315395797531814e-09, 'C24': 1.0627726743098556e-09, 'C25': 4.678806547858721e-10, 'C26': 2.1379245503740745e-10, 'C27': 9.798982653535273e-11, 'C28': 3.815742394994485e-11, 'C29': 2.080688978996437e-11, 'C30': 1.0550820693219559e-11, 'C31': 4.849357266347355e-12, 'C32': 2.2522906412776558e-12, 'C33': 1.0164783478067635e-12, 'C34': 5.156668462827241e-13, 'C35': 2.670893405417519e-13, 'C36': 1.717288561912755e-12}, liquid_z=0.3383720436823511, vapour_z=0.8735180438595676, vapour_molecular_mass=20.726264215931558, liquid_molecular_mass=124.86600334495657, vapour_volume=168.35813094528484, liquid_volume=116.50926295345467, vapour_molar_volume=469.13044759140143, liquid_molar_volume=181.72564312894582, vapour_density=0.04418017274799335, liquid_density=0.6871127332115493, vapour_viscosity=0.01736623894404342, liquid_viscosity=0.41922505636684787)}

In [44]:
krsnln_base_composition.BIPS

,CO2,N2,C1,C2,C3,iC4,nC4,iC5,nC5,C6,...,C27,C28,C29,C30,C31,C32,C33,C34,C35,C36
CO2,0.000,0.000,0.004,0.009,0.000,0.008,0.023,0.040,0,0.050,...,0,0,0,0,0,0,0,0,0,0
N2,0.000,0.000,0.003,0.011,0.000,0.010,0.026,0.044,0,0.054,...,0,0,0,0,0,0,0,0,0,0
C1,0.004,0.003,0.000,0.024,0.004,0.023,0.045,0.067,0,0.042,...,0,0,0,0,0,0,0,0,0,0
C2,0.009,0.011,0.024,0.000,0.009,0.000,0.003,0.011,0,0.017,...,0,0,0,0,0,0,0,0,0,0
C3,0.000,0.000,0.004,0.009,0.000,0.008,0.022,0.039,0,0.049,...,0,0,0,0,0,0,0,0,0,0
iC4,0.008,0.010,0.023,0.000,0.008,0.000,0.004,0.012,0,0.018,...,0,0,0,0,0,0,0,0,0,0
nC4,0.023,0.026,0.045,0.003,0.022,0.004,0.000,0.003,0,0.006,...,0,0,0,0,0,0,0,0,0,0
iC5,0.040,0.044,0.067,0.011,0.039,0.012,0.003,0.000,0,0.001,...,0,0,0,0,0,0,0,0,0,0
nC5,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C6,0.050,0.054,0.042,0.017,0.049,0.018,0.006,0.001,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C7,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C8,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C9,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C10,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C11,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C12,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C13,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C14,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C15,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C16,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C17,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C18,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C19,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C20,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C21,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C22,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C23,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C24,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C25,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C26,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C27,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C28,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C29,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C30,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C31,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C32,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C33,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C34,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C35,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0
C36,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0,0.000,...,0,0,0,0,0,0,0,0,0,0

In [54]:
krsnln_model.experiments.SEPARATORTEST.calculate([0.7, 0.5, 0.1], [20, 20, 20])

In [55]:
krsnln_model.experiments.SEPARATORTEST.result

{'Stage 1': TwoPhaseFlashResults(temperature=293.14, pressure=0.7, stable=False, EOS='PREOS', Fv=0.5415582716006995, Fl=0.45844172839930053, Ki={'N2': 71.19336849663392, 'CO2': 5.778937039008326, 'C1': 25.140692504093323, 'C2': 4.298644476347855, 'C3': 1.2039605965403546, 'iC4': 0.47492809075343184, 'nC4': 0.33012374394483324, 'iC5': 0.13114798810236278, 'nC5': 0.09738171004930117, 'C6': 0.03792529675382948, 'C7': 0.012082686738430637, 'C8': 0.004485529281973644, 'C9': 0.001536036385186933, 'C10': 0.0005400744966745858, 'C11': 0.00019936521095040627, 'C12': 7.112561360813915e-05, 'C13': 2.591278603829622e-05, 'C14': 9.091561332055799e-06, 'C15': 2.937278861497589e-06, 'C16': 1.0380728418722583e-06, 'C17': 3.5004907176456577e-07, 'C18': 1.4550791795202612e-07, 'C19': 6.286572444643133e-08, 'C20': 2.43100760557846e-08, 'C21': 9.022317552590214e-09, 'C22': 3.497275404322338e-09, 'C23': 1.3058303062929816e-09, 'C24': 5.058094325887703e-10, 'C25': 1.848908063223953e-10, 'C26': 6.624317696014363e-11, 'C27': 2.2784785321522268e-11, 'C28': 8.170241517362201e-12, 'C29': 3.1653753914737362e-12, 'C30': 1.3407963836457677e-12, 'C31': 5.06450350387526e-13, 'C32': 2.0352072780587867e-13, 'C33': 7.962118228452501e-14, 'C34': 3.3297030387295874e-14, 'C35': 1.2332402592370184e-14, 'C36': 4.8893148916215695e-15}, liquid_composition={'N2': 6.690609957737903e-05, 'CO2': 0.004133551309575885, 'C1': 0.02767018920250179, 'C2': 0.03710523847840628, 'C3': 0.0708878441433313, 'iC4': 0.0136673973746439, 'nC4': 0.04775885892182955, 'iC5': 0.0165088504705459, 'nC5': 0.03382710947906822, 'C6': 0.0467497950312593, 'C7': 0.06882628077792625, 'C8': 0.08708297698264528, 'C9': 0.06410763803028205, 'C10': 0.0552444814978895, 'C11': 0.04464520965797686, 'C12': 0.0378462015352588, 'C13': 0.036626606251885366, 'C14': 0.03219889437500673, 'C15': 0.02650538151612016, 'C16': 0.02323316701403234, 'C17': 0.019720936700364185, 'C18': 0.018695627042342622, 'C19': 0.017452163535281735, 'C20': 0.015008861635971774, 'C21': 0.012412851772452601, 'C22': 0.011191200476340332, 'C23': 0.01060218885753105, 'C24': 0.009707766324088592, 'C25': 0.008529744980883946, 'C26': 0.00791891929103985, 'C27': 0.007591691103355775, 'C28': 0.005999181498195249, 'C29': 0.006304594343773294, 'C30': 0.005802844715400073, 'C31': 0.005257464726946452, 'C32': 0.004603008675789017, 'C33': 0.003992182334623578, 'C34': 0.003708584831635818, 'C35': 0.0038394762368914193, 'C36': 0.046968137386694156}, vapour_composition={'N2': 0.0047632706018848284, 'CO2': 0.023887532765549453, 'C1': 0.6956477182701808, 'C2': 0.15950222842877101, 'C3': 0.08534617112226482, 'iC4': 0.006491030940708094, 'nC4': 0.015766333313807473, 'iC5': 0.0021651025250948395, 'nC5': 0.003294141767096588, 'C6': 0.001772999849741212, 'C7': 0.000831606390010953, 'C8': 0.0003906132432170923, 'C9': 9.84716645829068e-05, 'C10': 2.983613553902114e-05, 'C11': 8.900701641387673e-06, 'C12': 2.69183430693258e-06, 'C13': 9.490974111140283e-07, 'C14': 2.9273822303476014e-07, 'C15': 7.785369684322867e-08, 'C16': 2.4117719707949364e-08, 'C17': 6.903295586290241e-09, 'C18': 2.720361765738871e-09, 'C19': 1.0971429038030786e-09, 'C20': 3.648665678812215e-10, 'C21': 1.1199269042429965e-10, 'C22': 3.9138710170745477e-11, 'C23': 1.3844659523205808e-11, 'C24': 4.910279776091623e-12, 'C25': 1.577071427240037e-12, 'C26': 5.245743719294479e-13, 'C27': 1.7297505201727186e-13, 'C28': 4.901476174674599e-14, 'C29': 1.9956407789004495e-14, 'C30': 7.780433209266372e-15, 'C31': 2.6626448531120887e-15, 'C32': 9.368076757933546e-16, 'C33': 3.178622773781246e-16, 'C34': 1.2348486183284236e-16, 'C35': 4.7349966697183456e-17, 'C36': 2.2964201355649153e-16}, liquid_z=0.06457883428574142, vapour_z=0.9683030964412133, vapour_molecular_mass=22.88464342930346, liquid_molecular_mass=163.81519575355924, vapour_volume=1824.8811342315685, liquid_volume=103.02732164090638, vapour_molar_volume=3369.685645900513, liquid_molar_volume=224.7337344282283, vapour_density=0.006791328875779384, liquid_density=0.7289301544796595, vapour_viscosity=0.015606972915108585, liquid_viscosity=0.6056478555982026),
 'Stage 2': TwoPhaseFlashResults(temperature=293.14, pressure=0.5, stable=False, EOS='PREOS', Fv=0.5639604156574549, Fl=0.4360395843425451, Ki={'N2': 99.89419804296185, 'CO2': 7.974500393231731, 'C1': 35.00718284360509, 'C2': 5.90522323523037, 'C3': 1.6339677482640769, 'iC4': 0.6389228641884135, 'nC4': 0.4430218519550089, 'iC5': 0.17426069898682045, 'nC5': 0.1292135220533079, 'C6': 0.04971485442686626, 'C7': 0.015746908770059916, 'C8': 0.005789150995978266, 'C9': 0.0019611253822452747, 'C10': 0.000682085498238183, 'C11': 0.0002491490831980921, 'C12': 8.792373210974702e-05, 'C13': 3.170301186534362e-05, 'C14': 1.1003368040353291e-05, 'C15': 3.513416347126202e-06, 'C16': 1.2281639302566662e-06, 'C17': 4.095136366851665e-07, 'C18': 1.686715587717407e-07, 'C19': 7.224397804700177e-08, 'C20': 2.7663748569927774e-08, 'C21': 1.0163065347716321e-08, 'C22': 3.901769912714332e-09, 'C23': 1.4424721964777013e-09, 'C24': 5.534158155978602e-10, 'C25': 2.0023689906093788e-10, 'C26': 7.101237929180371e-11, 'C27': 2.4168996694919358e-11, 'C28': 8.579141508013349e-12, 'C29': 3.2931068315078068e-12, 'C30': 1.3833565380915516e-12, 'C31': 5.176961004525279e-13, 'C32': 2.0623392823419818e-13, 'C33': 7.996572227018588e-14, 'C34': 3.31639727176465e-14, 'C35': 1.2168884442964388e-14, 'C36': 4.782555041142345e-15}, liquid_composition={'N2': 4.597763249329135e-05, 'CO2': 0.0030063763957368954, 'C1': 0.019298510278848872, 'C2': 0.027451058236101014, 'C3': 0.05798598431748359, 'iC4': 0.01228199984572321, 'nC4': 0.04437038449313595, 'iC5': 0.016359007957898013, 'nC5': 0.03397790928785658, 'C6': 0.0482511511999572, 'C7': 0.07193020495679074, 'C8': 0.09135808108130467, 'C9': 0.06735272133021306, 'C10': 0.058068572911504336, 'C11': 0.04693485004045502, 'C12': 0.03978942159098498, 'C13': 0.038507949225241235, 'C14': 0.03385303945069456, 'C15': 0.02786710265793306, 'C16': 0.024426794646268814, 'C17': 0.020734125022619967, 'C18': 0.019656140144215118, 'C19': 0.01834879251633076, 'C20': 0.015779962801965985, 'C21': 0.013050579376544363, 'C22': 0.011766164056589883, 'C23': 0.011146891148473696, 'C24': 0.010206516407669095, 'C25': 0.00896797256969019, 'C26': 0.008325764855187042, 'C27': 0.007981724861352945, 'C28': 0.006307397845901061, 'C29': 0.006628501703973323, 'C30': 0.006100973986046074, 'C31': 0.005527574337209882, 'C32': 0.004839494690252461, 'C33': 0.004197286290714861, 'C34': 0.0038991185690034117, 'C35': 0.00403673470343871, 'C36': 0.04938119119556032}, vapour_composition={'N2': 0.0045928987258313635, 'CO2': 0.023974349750006462, 'C1': 0.6755864779408547, 'C2': 0.1621046269274857, 'C3': 0.09474722822611474, 'iC4': 0.007847250519391126, 'nC4': 0.019657049910104897, 'iC5': 0.002850732161474266, 'nC5': 0.004390405331091752, 'C6': 0.0023987989578345857, 'C7': 0.0011326783752662953, 'C8': 0.000528885726082498, 'C9': 0.00013208713136397354, 'C10': 3.96077314863237e-05, 'C11': 1.1693774857619303e-05, 'C12': 3.498434444767547e-06, 'C13': 1.2208179711978725e-06, 'C14': 3.7249745236059167e-07, 'C15': 9.790873402542606e-08, 'C16': 3.0000108116334e-08, 'C17': 8.490906941498012e-09, 'C18': 3.3154317975605523e-09, 'C19': 1.3255897637387897e-09, 'C20': 4.3653292339639995e-10, 'C21': 1.326338910293793e-10, 'C22': 4.590886490406322e-11, 'C23': 1.6079080558836698e-11, 'C24': 5.648447602163135e-12, 'C25': 1.7957190182183143e-12, 'C26': 5.912323717909115e-13, 'C27': 1.9291028179379499e-13, 'C28': 5.411205866732378e-14, 'C29': 2.1828364244015688e-14, 'C30': 8.43982225232331e-15, 'C31': 2.861603679335022e-15, 'C32': 9.980680006393093e-16, 'C33': 3.3563902981176324e-16, 'C34': 1.29310261845298e-16, 'C35': 4.912255813304979e-17, 'C36': 2.36168264889941e-16}, liquid_z=0.04771972372634486, vapour_z=0.97597483986154, vapour_molecular_mass=23.5918142199646, liquid_molecular_mass=170.1410668468523, vapour_volume=2681.595985796113, liquid_volume=101.37478370357653, vapour_molar_volume=4754.936536937537, liquid_molar_volume=232.48986409439897, vapour_density=0.004961541344810279, liquid_density=0.7318214387951515, vapour_viscosity=0.01557629269910429, liquid_viscosity=0.6149001179152376),
 'Stage 3': TwoPhaseFlashResults(temperature=293.14, pressure=0.1, stable=False, EOS='PREOS', Fv=0.6375585791675817, Fl=0.36244142083241826, Ki={'N2': 502.5617020819319, 'CO2': 38.68838106433851, 'C1': 173.08934690685092, 'C2': 28.417547093352354, 'C3': 7.640115926654293, 'iC4': 2.939005545687001, 'nC4': 2.0281439248335724, 'iC5': 0.7803129927895739, 'nC5': 0.5783148283903835, 'C6': 0.216059388155624, 'C7': 0.06784992858257617, 'C8': 0.02443413761118588, 'C9': 0.008089501504470879, 'C10': 0.0027494111374047996, 'C11': 0.0009820798305242942, 'C12': 0.0003386507829734852, 'C13': 0.00011945673152865378, 'C14': 4.0519346954659985e-05, 'C15': 1.2619313795486934e-05, 'C16': 4.309888643273827e-06, 'C17': 1.4031416973701294e-06, 'C18': 5.667843175414427e-07, 'C19': 2.3833163894290842e-07, 'C20': 8.938066567958257e-08, 'C21': 3.213524098055495e-08, 'C22': 1.2088173764669521e-08, 'C23': 4.375829078342858e-09, 'C24': 1.6450802437408076e-09, 'C25': 5.824623304961214e-10, 'C26': 2.0213837065049575e-10, 'C27': 6.727617708297802e-11, 'C28': 2.3372459996591038e-11, 'C29': 8.796787492465564e-12, 'C30': 3.6307806807191393e-12, 'C31': 1.3322674222296385e-12, 'C32': 5.210146218729827e-13, 'C33': 1.9823374848838885e-13, 'C34': 8.07754064937938e-14, 'C35': 2.9057857037031755e-14, 'C36': 1.1210840544220247e-14}, liquid_composition={'N2': 8.137359263503827e-06, 'CO2': 0.0005925825890698422, 'C1': 0.0035172449250605456, 'C2': 0.005594626899839486, 'C3': 0.015041259025204238, 'iC4': 0.004373869607012555, 'nC4': 0.018382969286033383, 'iC5': 0.01016455687107128, 'nC5': 0.023650009685206523, 'C6': 0.04476729410867847, 'C7': 0.07888396386402972, 'C8': 0.10616912121482049, 'C9': 0.080095289643964, 'C10': 0.06958519503770609, 'C11': 0.05638633110861333, 'C12': 0.04784609152738604, 'C13': 0.046319625651682295, 'C14': 0.04072499005064059, 'C15': 0.03352526683972648, 'C16': 0.02938677795052298, 'C17': 0.024944394350566, 'C18': 0.023647541396115627, 'C19': 0.022074732068286394, 'C20': 0.01898427494757031, 'C21': 0.01570065845904672, 'C22': 0.014155427350313502, 'C23': 0.013410403655255478, 'C24': 0.012279074373096903, 'C25': 0.010789029078708053, 'C26': 0.010016413238570382, 'C27': 0.00960251171785087, 'C28': 0.007588192123876614, 'C29': 0.007974500047880417, 'C30': 0.007339851374708093, 'C31': 0.006650015913964488, 'C32': 0.005822213278818269, 'C33': 0.0050495966089255055, 'C34': 0.004690882284440896, 'C35': 0.004856443058152371, 'C36': 0.05940864604768058}, vapour_composition={'N2': 0.004089525121918659, 'CO2': 0.022926061018026366, 'C1': 0.6087976269901657, 'C2': 0.15898557339592448, 'C3': 0.11491696263539553, 'iC4': 0.012854827031121722, 'nC4': 0.03728330747787076, 'iC5': 0.007931535792445456, 'nC5': 0.01367715129253112, 'C6': 0.009672394174503942, 'C7': 0.005352271314484936, 'C8': 0.0025941509178215977, 'C9': 0.0006479309660758776, 'C10': 0.00019131831023515433, 'C11': 5.5375878499033716e-05, 'C12': 1.620311635797032e-05, 'C13': 5.533191085980757e-06, 'C14': 1.650150001586982e-06, 'C15': 4.23065862327941e-07, 'C16': 1.2665374055136869e-07, 'C17': 3.5000519828923044e-08, 'C18': 1.3403055611730411e-08, 'C19': 5.2611070730602744e-09, 'C20': 1.6968271322580565e-09, 'C21': 5.045444431348549e-10, 'C22': 1.7111326552374505e-10, 'C23': 5.868163426698227e-11, 'C24': 2.0200062662605755e-11, 'C25': 6.284203020974714e-12, 'C26': 2.0247014518066724e-12, 'C27': 6.460202787715066e-13, 'C28': 1.7735471686175338e-13, 'C29': 7.014998227986048e-14, 'C30': 2.664939057063996e-14, 'C31': 8.859599559483541e-15, 'C32': 3.0334582499273594e-15, 'C33': 1.0010004641415598e-15, 'C34': 3.7890792334024943e-16, 'C35': 1.411178280922769e-16, 'C36': 6.660208577885674e-16}, liquid_z=0.010754127889136602, vapour_z=0.9938139973895194, vapour_molecular_mass=26.95311882660868, liquid_molecular_mass=193.9869265394596, vapour_volume=15434.810815061857, liquid_volume=94.94872305702386, vapour_molar_volume=24209.24338468486, liquid_molar_volume=261.969845606927, vapour_density=0.0011133399916025313, liquid_density=0.7404933422395781, vapour_viscosity=0.015512953545991678, liquid_viscosity=0.6394946640842553)}

In [57]:
from calculations.Utils.ResultsViewer import SeparatorTestResultsViewer

sep_test_view = SeparatorTestResultsViewer()
sep_test_view.view(krsnln_model.experiments.SEPARATORTEST.result)

AttributeError: 'dict' object has no attribute 'first_stage_pressure'